### ISSUE TITLE
`validate-genesis` must accept the now removed `max_wasm_code_size` chain param

### ISSUE THREAD

**Issue by pwnfoo** [CosmWasm/wasmd#1485]
### What?

Chains which were initialized with previous versions of wasmd still have `max_wasm_code_size` as chain parameter

As a result, `validate-genesis` on the new wasmd complains that it is not an acceptable parameter, fails and also throws usage for some reason.

For eg: 

```
nyxd validate-genesis
Error: error validating genesis file /path/to/.nyxd/config/genesis.json: unknown field "max_wasm_code_size" in types.Params
Usage:
  nyxd validate-genesis [file] [flags]

Flags:
  -h, --help   help for validate-genesis


Global Flags:
--- SNIP ---
```

### Why?

It would be nice if new versions of wasmd is backwards-compatible with old genesis files and doesn't break `validate-genesis`, since it's an important step to verify the genesis file.

Instead of erroring out, it could be a warning saying that this parameter is now a compile-time variable instead.

**Comment by alpe** [comment]
Thanks for bringing this up and I apologize for the inconvenience!
I think it is important to manage expectations first: a genesis export from one major version is not supposed to work out of the box in a newer version. Although this would be nice, we only have this supported on the same version.

We had a very stable api in the past but the SDK is moving fast and the step from SDK 45 to 47 was touching a lot of code.
Nevertheless you are pointing to a valid UX problem! I asked and the SDK team addresses this with the `genesis migrate` [command](https://docs.cosmos.network/main/migrations/intro) which was introduced to upgrade the genesis from the previous version, now.
It will be opened with SDK 50 so that other modules can integrate with it. This would make sense for us, too. 
I will open a new ticket to follow up on this.

**Comment by alpe** [comment]
I am closing this now. Work is tracked in #1490
