### ISSUE TITLE
Store events for gov proposals

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1527]
To provide the same data as with user messages:
* storing code 
* updating 
* clearing an admin

**Comment by pysel** [comment]
hello @alpe. is this available to pick up?

**Comment by pinosu** [comment]
Hi @pysel, sure feel free to take this task! 👍

**Comment by pysel** [comment]
hey. I have a small question on this one:

since (for example) code storing messages (`MsgStoreCode`) that come to the module from a proposal (gov module) or directly from a user are indistinguishable from one another, I cannot really think of any way to implement this event emission w/o state breaking changes.

I think the easiest way to do that is to add a field to `MsgStoreCode` that would indicate whether this particular message was sent from gov module or just from a user. If changing `MsgStoreCode` is not worth it for this, lmk, I will think of something else (or if there is already a desired way to address this, please, lmk)

cc: @pinosu @alpe

**Comment by pysel** [comment]
hey @pinosu, may I have more context on this one? 

1. should events be emitted when mentioned proposals are executed or only created?
2. afaiu from the issue, events are already emitted for mentioned messages when a user sends them. but first, afaik listed messages are not distinguishable whether they were sent from a user or from gov module to handle when msg_server receives them. and second, I do not really see where the said events get emitted.

thanks in advance for clarification!

**Comment by pinosu** [comment]
Hi @pysel , this issue has become not so relevant for the next releases because v1beta1 gov proposals are deprecated.
If you would like to complete it anyway, we could probably include it in the next v0.34 release.
Here some more context:
There are few proposal handlers where events are not emitted and should be added such as :
- https://github.com/CosmWasm/wasmd/blob/78b5af29a26a2752b9216868246a3e7105086030/x/wasm/keeper/proposal_handler.go#L71
- https://github.com/CosmWasm/wasmd/blob/78b5af29a26a2752b9216868246a3e7105086030/x/wasm/keeper/proposal_handler.go#L273
- https://github.com/CosmWasm/wasmd/blob/78b5af29a26a2752b9216868246a3e7105086030/x/wasm/keeper/proposal_handler.go#L290

**Comment by pysel** [comment]
> * handleStoreCodeProposal

ah, thanks @pinosu, makes sense now. I am ok to work on this if this is actually needed, if wasmd plans to migrate from v1beta1 proposals soon, then, I suppose, it might not be worth it. either way, let me know please!

**Comment by pinosu** [comment]
@pysel thank you. I think it is not so relevant anymore. I will just close this issue 👍
