### ISSUE TITLE
Separate types into separate package

### ISSUE THREAD

**Issue by conorpp** [CosmWasm/wasmd#1552]
I'd like to use just the type definitions and compiled proto files.  My team is running into recurring issues by depending on the full wasmd package due to the use of the precompiled shared library.  We'd like to deploy to lightweight cloud environments like Google App Engine, but due to the precompiled share lib, it's a no go to use wasmd as a dependency.  

However, if we can split x/wasm/types into a separate package, problem is solved for us.  Some of the imported wasmvm types would also need to be moved.

Would this project accept a PR to make the split?

**Comment by alpe** [comment]
Thanks @conorpp for bringing this topic up. Happy to see more use cases!

Do you mean `libwasmvm` with "precompiled shared library"? It is only required for environments where the wasmVM (and CGO) is used. For a pure client use-case (or an indexer for example) the `CGO_ENABLED=0` can be set in the build environment so that you don't have this dependency.
If this is not solving your problem, can you elaborate a bit more on your use case and link to your code, please? The changes in your PR add quite some complexity to this project and there may be a simpler solution.

**Comment by conorpp** [comment]
Okay awesome, will try that.  Thanks!
