### ISSUE TITLE
Why can't the value in add_attribute be “”?

### ISSUE THREAD

**Issue by 99Kies** [CosmWasm/wasmd#1617]
I think the need for event's value to be "" should still be quite high.
https://github.com/CosmWasm/wasmd/blob/main/x/wasm/keeper/events.go#L57-L61

https://github.com/CosmWasm/cosmwasm/issues/1869

https://github.com/CosmWasm/wasmd/pull/1618

I don't know why it can't be `""`, I think it's still necessary to remove that part of the code.

If it's a judgment about add_attribute not being able to be "" it shouldn't be in `wasmd`, you should put it in `cosmwasm-std`.
https://github.com/CosmWasm/cosmwasm/blob/7b2e753e4752eeb2466a7411ec8e177147581c40/packages/std/src/results/events.rs

**Comment by 99Kies** [comment]
If you want to add judgments, shouldn't they all be added in `cosmwasm-std`, why here.
https://github.com/CosmWasm/wasmd/blob/main/x/wasm/keeper/events.go#L53-L61

https://github.com/CosmWasm/cosmwasm/blob/7b2e753e4752eeb2466a7411ec8e177147581c40/packages/std/src/results/events.rs#L70-L117

**Comment by alpe** [comment]
Thanks for bringing this up for discussion. Can you elaborate a bit more on your use case?

**Comment by 99Kies** [comment]
@alpe I need to add relevant title, description and link information to my Proposal. Since I have a cosmwasm-starter(https://github.com/DoraFactory/cosmwasm-starter) synchronization script under the chain, I will synchronize the latest data to the database based on the event that is triggered. This way the front end can directly access the back end api to get the data.

**Comment by 99Kies** [comment]
@alpe In addition to the need that the indexer will depend on the event, the event will also be displayed in the transaction body, and for some `set` operations, I think the user will want to know the final result. (These results can only be displayed in event, and some of them will definitely be `""` as well)


such as: `set_description(description: string)`, `set_note(note: string)`, `set_img_url(img_url: string)` etc.

**Comment by lshoo** [comment]
i think the event is a key/value pair, if the value is null, don't emit the event

**Comment by webmaster128** [comment]
I agree with @99Kies here. It is irritating that an attribute value cannot be empty. You can easily have applications where an attribute value may be empty and then it is nice to just emit it instead of having to add extra logic to omit it.

This problem is not easily visible during the contract development process and only pops up late when the contract is on chain. Even worse, it can remain undetected for a long time because usually a field is set and then cause transaction failures when the value is empty.

I think it would be good to just verify that empty attribute values are not causing an issue in the SDK and then remove the check in the next consensus-breaking release.

> i think the event is a key/value pair, if the value is null, don't emit the event

An event contains a list of attributes (i.e. a list of key/value pairs). Not emitting the event has a different meaning than not adding an attribute to the list of an event.

**Comment by alpe** [comment]
ok, let's accept empty values. I don't have the client in mind but the contract devs that may not check the value before passing it to the event. I saw this recently and thought about this again.

**Comment by alpe** [comment]
There are also whitespaces allowed in the PR #1618.  I assume it is the same argument to support them.

**Comment by webmaster128** [comment]
Whitespace is trimmed away in all cases. Then I think it's consistent to do that in whitespace-only cases as well. This diff in the PR looks good to me.
