### ISSUE TITLE
Missing root_v2.go file

### ISSUE THREAD

**Issue by ComputerKeeda** [CosmWasm/wasmd#1901]
Hello,

I am currently exploring the wasmd repository and have come across references to a file named root_v2.go. However, I am unable to locate this file within the repository.

Could you please provide some guidance on where root_v2.go is located, or if it has been moved or deprecated? Any information or clarification would be greatly appreciated.

Thank you for your assistance!

**Comment by pinosu** [comment]
Hey @ComputerKeeda, could you share the reference where root_v2.go is mentioned?

**Comment by chipshort** [comment]
It's mentioned in [encoding.go](https://github.com/CosmWasm/wasmd/blob/5657a0158afc1fb7996f2a8ba82c48a3aeafcd00/app/encoding.go#L20) and [root.go](https://github.com/CosmWasm/wasmd/blob/5657a0158afc1fb7996f2a8ba82c48a3aeafcd00/cmd/wasmd/root.go#L39).
I poked around in the git history a little, but didn't see any root_v2 file.

**Comment by pinosu** [comment]
Hey @ComputerKeeda , it is a reference to the deepinject implementation tracked in #1286 that unfortunately has been blocked for some time. 
We will support deepinject in future releases, so at the moment you can ignore the reference.
I will close this issue because you can follow the deepinject support in the issue mentioned above.
