### ISSUE TITLE
Return error if wasm to big

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#287]
Currently it cuts of the wasm at 400kb, but doesn't return an error, leading to odd error messages.

We can raise the size limit a bit, maybe 600kb. But mainly, we need to return an error on the limit. Not sure how to do it with this interface.

https://github.com/CosmWasm/cosmwasm/issues/576#issuecomment-706766984

**Comment by webmaster128** [comment]
> Not sure how to do it with this interface.

If there is no fancy API for that, you can set `maxSize` to the max Wasm size that is allowed and read up to `maxSize + 1` bytes. Now if the result length is `> maxSize`, then the Wasm exceeded the limit. Like

```go
decompressed = ioutil.ReadAll(io.LimitReader(zr, maxSize +1))
if len(decompressed) > maxSize {
  // error
}
return decompressed
```

**Comment by webmaster128** [comment]
Since this is probably censensus breaking, I suggest adding this to 0.12.0.

**Comment by webmaster128** [comment]
Changing the value if the limit is now tracked here: https://github.com/CosmWasm/wasmd/issues/289

**Comment by ethanfrey** [comment]
I think leaving the same limit and returning a better error message is not consensus breaking. As long as it still succeeds at 400kb and fails at 400kb+1. The error message is not part of consensus (the code is however, so we make sure we return the same error code).

The further improvements (adjustable limit, new code, etc) should definitely be in 0.12. I would like to pull a non breaking part into 0.11 to avoid confusion from new devs

**Comment by webmaster128** [comment]
The error code is one thing to check. In addition to that, I am realtively sure you can create a large Wasm file that is perfectly valid when truncating after 400 bytes. This way cou can attack consesus. Would be a nice side-challenge for the hacaktom.

We can do this in a patch release, but add a big warning. Since there is no large 0.11 network yet, I assume we don't have to expect 0.11.1 and 0.11.2 mixed networks.
