### ISSUE TITLE
Add a client for Windows

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#315]
Add a wasmcli for Windows.
See https://github.com/CosmWasm/wasmd/pull/312#issuecomment-728147640

Current workaround would be to use the docker image

**Comment by webmaster128** [comment]
Copying over from chat:

> I think it is important to have the same binary name (wasmd/wasmd.exe) for both UNIX and Windows for documentation reasons.
> IIRC, a documentation like `wasmd query wasm contract-history cosmos18r5szma8hm93pvx6lwpjwyxruw27e0k5uw835c` will work on Windows, even if the binary is called wasmd.exe

Then we can have a wasmd, which is not a deamon and only includes a client. But hey, who cares.

**Comment by webmaster128** [comment]
> Interestingly, `wasmvm` can be built on Windows and it generates a `wasmvm.dll` file. (The included `Makefile` assumes it's called `libwasmvm.dll` so the copy command breaks.) So, in theory, implementing Windows compatibility shouldn't be a hard task.

Since 1.0 or so Wasmer supports cross-compilation. So you can compile the Wasm compiler (Wasmer/singlepass) on Windows and get a `.dll`. However the compilation `target` cannot be Windows and you'll get an [unsupported OS error at runtime](https://github.com/wasmerio/wasmer/blob/2.0.0/lib/compiler-singlepass/src/compiler.rs#L59-L63) when trying to do so.

The ticket Ethan linked is promising but untested and unreleased.

**Comment by alpe** [comment]
We have windows client support now: https://github.com/CosmWasm/wasmd/pull/1197 

> I think it is important to have the same binary name (wasmd/wasmd.exe) for both UNIX and Windows for documentation reasons.

The argument makes sense. I will rename the `wasmd-client.exe` binary
