### ISSUE TITLE
Question: Reason to query `Keeper` directly rather than using `Querier`.

### ISSUE THREAD

**Issue by whylee259** [CosmWasm/wasmd#379]
This is not a bug report nor a proposal, just a question.

In the `QueryPlugins`, the built-in plugins (Bank, Staking, Wasm) are querying keepers directly rather than using queriers that each module offers.
Calling keeper directly can query things that the module does not open for query purposes.
Also, the staking plugin calls the distribution keeper beyond the scope of the staking module. (adding the distribution plugin is not good?)

Can I know the reason to use 'Keeper' rather than `Querier`

**Comment by ethanfrey** [comment]
This has been the standard design of the cosmos sdk since "forever"... early 2018 I guess. Only in stargate is it even possible/meaningful to get cleanly formatted data from the querier.

There is a discussion upstream to change that: https://github.com/cosmos/cosmos-sdk/pull/7459  You are welcome to comment and review it.

As to why `wasmd` does it? Because that is the way all the other Cosmos SDK modules do it, and we aim to stay as standard as possible, so we can easily track all changes in the sdk design

**Comment by ethanfrey** [comment]
Looks like this answered your question.
Closing it for now, but feel free to reopen/comment if you have more questions here.
