### ISSUE TITLE
Fix Parameter change via proposal 

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#392]
### Scenario:
Change value for the `instantiateAccess` parameter from `AccessTypeOnlyAddress` with an address to a value without address like `AccessTypeNobody`. 

### Issue
It fails with `invalid parameter value: address not allowed for this type`. 

### Cause
The `address` part from the previous state was not cleared by the gov parameter change proposal handler. Probably because it is set to an empty value.

This can be replicated in a modified `TestUpdateParamsProposal` test.

**Comment by alpe** [comment]
@bragaz fyi: you may run into this with simulations

**Comment by bragaz** [comment]
During the weekend I've tried to solve this but somehow it kept returning this error so this morning I asked my @riccardom to help me debug the code.  
We found out that protobuf takes care of the unmarshal while we were using `json.Marshal` to encode the `CodeUploadAccess` param inside `ParamChanges`.
After switching to protobuf marshaler everything worked fine.
However, the tests will fail due to a bug inside the `Capability` module but I don't think this is related to the params.
