### ISSUE TITLE
Filter out Message events before calling submessage response 

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#448]
Follow up from https://github.com/CosmWasm/wasmd/pull/441#discussion_r590474261

**Comment by ethanfrey** [comment]
I actually depend on the message event from submessage being present in the reply: https://github.com/CosmWasm/cosmwasm/blob/main/contracts/ibc-reflect/src/contract.rs#L39-L94

I didn't know a more reliable way to get the contract address from a newly created contract

**Comment by alpe** [comment]
The Instantiate method returns the address but it is in a protobuf type: https://github.com/CosmWasm/wasmd/blob/v0.16.0/x/wasm/keeper/msg_server.go#L72

**Comment by ethanfrey** [comment]
I have seen TerraSwap parses the InstantiateMsg data field. I can also hand-write a parser that doesn't involve prost/protobuf library. We should add something like this to `cosmwasm-std` as a utility.

**Comment by ethanfrey** [comment]
I think we also need a larger discussion about Events. There are 2 usages of Events now - for reply and to return to clients. Do we need the same rules for both of them?

Also, many of our rules are to work around the fact that Tendermint would flatten them, so all `wasm` type events get merged into one (appending the attributes) rather than as separate events. This is [fixed on master](https://github.com/tendermint/tendermint/pull/6634) (targetted for Tendermint 0.35, which is likely Cosmos SDK 0.44). 

So, I would like to remove workarounds inspired by the poor Tendermint behavior in the API we expose to contracts, which should be stable. That is - `reply` message body. I would like to choose a design for reply that works great for contracts. We can then filter/mangle the events we return to the client if it needs to be different. That said, I would not filter out any info inside the keeper for reply.
