### ISSUE TITLE
Events/ event attributes on reply

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#552]
Currently we append them as new custom events or wasm event (with attributes). 
This means there can be duplicate events for `wasm` or custom event types. Not sure if this is (still) an issue for Tendermint. 

I would also be important to document the desired behaviour in cosmwasm. On Reply the `data` would be overwritten but events/attributes are not.

**Comment by ethanfrey** [comment]
This definitely needs documentation. The whole events system does.

Tendermint does still have this issue... It will improve in 0.35, see [comment](https://github.com/CosmWasm/wasmd/issues/448#issuecomment-888083059) and https://github.com/tendermint/tendermint/pull/6634

It would also be good to write some tests to demonstrate expected behavior as those seem to stay up-to-date much better than docs. (And are always more clear)

**Comment by ethanfrey** [comment]
Defined in #581 
Closed by #586 

We will have multiple `wasm` events, but separated by the various entry point events
