### ISSUE TITLE
Allow contract Info query from the contract

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#584]
This idea comes originally from https://github.com/terra-money/core/issues/519

**Comment by ethanfrey** [comment]
Let's discuss if we want to do this.
If so, I would push it to a 0.19.0 release and only have gas adjustments before the final 1.0

**Comment by alpe** [comment]
IMHO it makes sense to provide this information via query. I don't have a concrete use case but contracts would be compatible between chains. It is not hard to build and this data may enable some exotic workflows where the some other contract's creator/admin could be used for authZ. 🤷‍♀️ 

This would have been nice contribution by terra devs

**Comment by husio** [comment]
I will take this task if that is ok. I think this is a great first issue, because I will write my first VM interaction code and a contract that validates introduced modification.

Please let me know if I understand the task correctly: `wasmd` (keeper->query) must be modified to support an additional call that returns "self" info. In other words, a contract can query information about itself only (not other contracts). Query call is done via JSON encoded message. Is this correct?

To test it, I should write a contract that executes a new query call. Contracts are currently implemented only in rust. Should I modify the existing hackatom and add another switch to it?

**Comment by alpe** [comment]
In wasmd new "native" queries can be added to the `query_plugins.go`. This new one can go into the 
["wasm"](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/keeper/query_plugins.go#L461) section. You will notice that the [wasmvm queries](https://github.com/CosmWasm/wasmvm/blob/12c336647f937183884fa52997ca9486d9a219e8/types/queries.go#L346) do not support this query type yet. For local testing you can use a branch and add the object

>  a contract can query information about itself only (not other contracts)

Let's not limit this and query any ContractInfo

> To test it, I should write a contract that executes a new query call

That would give us most confidence but is too complex to start with. Especially as the bindings are not done yet. 
When the request/ response types are defined (by you), let's have some unit tests to cover the wasmd (only) parts

**Comment by ethanfrey** [comment]
I would honestly wait until there was agreement with cosmwasm team as to if and how the QueryRequest object would be modified.

You can write something, but it is hard to integrate or even do full testing until there are clear spec

**Comment by assafmo** [comment]
This would be very useful for us! on Secret Network when contract A sends a message to contract B, for security reasons A must know B's data hash.
