### ISSUE TITLE
Increase contract `label` size

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#766]
We have a hard limit of max [`128` chars](https://github.com/CosmWasm/wasmd/blob/v0.23.0/x/wasm/types/validation.go#L11) currently for labels. With the change from 20 to 32 byte addresses, this is not long enough to contain two bech32 addresses anymore. 

Before: 128 > 2*45 char
Now: 128> 2*65 

Not sure how common this use case is. We had on example in the DeFi contracts to ensure a non empty label.

**Comment by maurolacy** [comment]
See https://github.com/confio/tfi/pull/69 for a fix at the contracts level.

**Comment by webmaster128** [comment]
128 bytes (assuming 1 byte per character which does not hold for asian languages) is about this much:

> We have a hard limit of max 128 chars currently for labels. With the change from 20 to 32 byte addresses, this is not long enou…

Assuming the label is supposed to be a user friendly string that can nicely be displayed in tools like a code explorers in order to show many instances of one code, I would not increase it. It already seems a bit too long but still managable.

**Comment by ethanfrey** [comment]
Yes, I think we should not abuse labels so much and focus on shorter representations.
