### ISSUE TITLE
Add operations to run with Simulations

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#797]
Current simulation setup does mutate the genesis state but does not provide any "WeightedOperations" (see [staking](https://github.com/cosmos/cosmos-sdk/blob/v0.45.1/x/staking/simulation/operations.go#L27))

Would be nice to have some examples to run

**Comment by alpe** [comment]
We have the basic create, instantiate, execute operations [covered](https://github.com/CosmWasm/wasmd/blob/main/x/wasm/simulation/operations.go) already. 
Missing are:
- migrate
- update admin
- clear admin

and all [gov proposals](https://github.com/CosmWasm/wasmd/blob/main/proto/cosmwasm/wasm/v1/proposal.proto)

There was no strong demand from the community to have more. Let's move this to some future release

**Comment by ethanfrey** [comment]
I would move this to v0.30 to trim down the v0.29 release

**Comment by GNaD13** [comment]
Hi @alpe , in the simulation for instantiate contract, I see that Admin is a random account
https://github.com/CosmWasm/wasmd/blob/98580347b78085d0c4b2fe2afa7f57ee91d60e7c/x/wasm/simulation/operations.go#L185
The problem is, if Admin is a random account like that, I can't find the way to (migrate, update or clear admin) because the sender of these 3 msg must be admin.
Can you check about this?
