### ISSUE TITLE
[Ask for help] What does supportedFeatures mean?

### ISSUE THREAD

**Issue by yann-sjtu** [CosmWasm/wasmd#924]
Hello, what does `supportedFeatures` mean?
https://github.com/CosmWasm/wasmd/blob/288609255ad92dfe5c54eae572fe7d6010e712eb/app/app.go#L510

I deleted `staking` in `supportedFeatures` and tried to upload the [escrow](https://github.com/InterWasm/cw-contracts/tree/main/contracts/escrow) contract. And I got an error as below.
```
"create wasm contract failed: Error calling the VM: Error during static Wasm validation: Wasm contract requires unsupported features: {\"staking\"}: failed to execute message; message index: 0"
```

**Comment by alpe** [comment]
"features" are annotations to enable specific operations in the stdlib that would otherwise not be available for contracts.  See https://github.com/CosmWasm/cosmwasm `#[cfg(feature = "iterator")]` for example.
Sorry for my late response. Please join our [discord](https://chat.cosmwasm.com/) to get faster feedback
