### ISSUE TITLE
Upgrade to wasmvm 1.1.1

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#980]
- [x] https://github.com/CosmWasm/wasmvm/pull/347 is merged
- [x] wasmvm 1.1.0 is tagged.
- [x] Update wasmvm (go.mod, Dockerfile)
- [x] Features have been renamed to capabilities. Rename all "supported features" variables to "available capabilities".
- [x] Finalize and merge https://github.com/CosmWasm/wasmd/pull/903
- [x] Add `cosmwasm_1_1` to available capabilities
- [x] Add integration test to cover new supply query
- [x] Doc new `cosmwasm_1_1`

This ticket closes https://github.com/CosmWasm/wasmd/issues/932

**Comment by webmaster128** [comment]
Here we go: https://github.com/CosmWasm/wasmvm/releases/tag/v1.1.0 is ready for integration.

**Comment by webmaster128** [comment]
What do you think needs to be done for "Doc new cosmwasm_1_1"? Do you have a list of capabilities somewhere already? For users of wasmd I don't think this is terribly important since they should just use or append to the wasmd defaults and wasmd implements cosmwasm_1_1 now.

How does appending to defaults work by the way? I hope users do not need to list our defaults when adding their capabilities.

**Comment by alpe** [comment]
I have added some notes to the [changelog](https://github.com/CosmWasm/wasmd/pull/1024) but it would be good to have a better place for them in the future. IMHO it makes sense to list and describe them im cosmwasm where they are defined. In this case, I could link to them from the source code and maybe some integration doc
